stages:
    - build

job:
    stage: build
    tags: 
        - csharp
    script:
        - echo "Restoring packages"
        - '.build\nuget.exe restore ReactTs.sln'
        - 'npm install'
        - '.build\MSBuild.exe ReactTS.sln /p:configuration=Release /clp:ErrorsOnly /m'
